import { Inter, Comforter, Noto_Sans_TC } from 'next/font/google'
import './globals.css'
import { Provider } from './provider'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

// const engFontType = Comforter({ weight: ['400'], subsets: ['latin'] })
const cnFontType = Noto_Sans_TC({ weight: ['400', '700', '900'], subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={cnFontType.className}>
        <Provider>
          <div className='flex flex-col justify-between h-screen'>
            <Header />
            {children}
            <Footer />
          </div>
        </Provider>
      </body>
    </html>
  )
}

export default RootLayout
