import test from '@/assets/icon-default-image.svg'
import Image from 'next/image'

//
export const metadata = {
  title: 'home',
  description: 'Generated by YWJ'
}

//
const testFetch = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/todos/1')
  const data = await res.json()
  return data
}

//
const Home = async () => {
  // throw new Error('error test')
  const data = await testFetch()

  console.log('資料', data)

  return (
    <div>
      首頁
      <Image src={test} alt='' />
    </div>
  )
}

export default Home
